package buildingsmart.ifc;

public enum IfcActuatorTypeEnum {
    ELECTRICACTUATOR,
    HANDOPERATEDACTUATOR,
    HYDRAULICACTUATOR,
    PNEUMATICACTUATOR,
    THERMOSTATICACTUATOR,
    USERDEFINED,
    NOTDEFINED,
}
