package buildingsmart.ifc;

public enum IfcAirToAirHeatRecoveryTypeEnum {
    FIXEDPLATECOUNTERFLOWEXCHANGER,
    FIXEDPLATECROSSFLOWEXCHANGER,
    FIXEDPLATEPARALLELFLOWEXCHANGER,
    ROTARYWHEEL,
    RUNAROUNDCOILLOOP,
    HEATPIPE,
    TWINTOWERENTHALPYRECOVERYLOOPS,
    THERMOSIPHONSEALEDTUBEHEATEXCHANGERS,
    THERMOSIPHONCOILTYPEHEATEXCHANGERS,
    USERDEFINED,
    NOTDEFINED,
}
