package buildingsmart.ifc;

public enum IfcCompressorTypeEnum {
    DYNAMIC,
    RECIPROCATING,
    ROTARY,
    SCROLL,
    TROCHOIDAL,
    SINGLESTAGE,
    BOOSTER,
    OPENTYPE,
    HERMETIC,
    SEMIHERMETIC,
    WELDEDSHELLHERMETIC,
    ROLLINGPISTON,
    ROTARYVANE,
    SINGLESCREW,
    TWINSCREW,
    USERDEFINED,
    NOTDEFINED,
}
