package buildingsmart.ifc;

public enum IfcCoilTypeEnum {
    DXCOOLINGCOIL,
    WATERCOOLINGCOIL,
    STEAMHEATINGCOIL,
    WATERHEATINGCOIL,
    ELECTRICHEATINGCOIL,
    GASHEATINGCOIL,
    USERDEFINED,
    NOTDEFINED,
}
