package buildingsmart.ifc;

public enum IfcCondenserTypeEnum {
    WATERCOOLEDSHELLTUBE,
    WATERCOOLEDSHELLCOIL,
    WATERCOOLEDTUBEINTUBE,
    WATERCOOLEDBRAZEDPLATE,
    AIRCOOLED,
    EVAPORATIVECOOLED,
    USERDEFINED,
    NOTDEFINED,
}
