package buildingsmart.ifc;

public enum IfcControllerTypeEnum {
    FLOATING,
    PROPORTIONAL,
    PROPORTIONALINTEGRAL,
    PROPORTIONALINTEGRALDERIVATIVE,
    TIMEDTWOPOSITION,
    TWOPOSITION,
    USERDEFINED,
    NOTDEFINED,
}
