package buildingsmart.ifc;

public enum IfcDamperTypeEnum {
    CONTROLDAMPER,
    FIREDAMPER,
    SMOKEDAMPER,
    FIRESMOKEDAMPER,
    BACKDRAFTDAMPER,
    RELIEFDAMPER,
    BLASTDAMPER,
    GRAVITYDAMPER,
    GRAVITYRELIEFDAMPER,
    BALANCINGDAMPER,
    FUMEHOODEXHAUST,
    USERDEFINED,
    NOTDEFINED,
}
