package buildingsmart.ifc;

public enum IfcEvaporativeCoolerTypeEnum {
    DIRECTEVAPORATIVERANDOMMEDIAAIRCOOLER,
    DIRECTEVAPORATIVERIGIDMEDIAAIRCOOLER,
    DIRECTEVAPORATIVESLINGERSPACKAGEDAIRCOOLER,
    DIRECTEVAPORATIVEPACKAGEDROTARYAIRCOOLER,
    DIRECTEVAPORATIVEAIRWASHER,
    INDIRECTEVAPORATIVEPACKAGEAIRCOOLER,
    INDIRECTEVAPORATIVEWETCOIL,
    INDIRECTEVAPORATIVECOOLINGTOWERORCOILCOOLER,
    INDIRECTDIRECTCOMBINATION,
    USERDEFINED,
    NOTDEFINED,
}
