package buildingsmart.ifc;

public enum IfcEvaporatorTypeEnum {
    DIRECTEXPANSIONSHELLANDTUBE,
    DIRECTEXPANSIONTUBEINTUBE,
    DIRECTEXPANSIONBRAZEDPLATE,
    FLOODEDSHELLANDTUBE,
    SHELLANDCOIL,
    USERDEFINED,
    NOTDEFINED,
}
