package buildingsmart.ifc;

public enum IfcElectricDistributionPointFunctionEnum {
    ALARMPANEL,
    CONSUMERUNIT,
    CONTROLPANEL,
    DISTRIBUTIONBOARD,
    GASDETECTORPANEL,
    INDICATORPANEL,
    MIMICPANEL,
    MOTORCONTROLCENTRE,
    SWITCHBOARD,
    USERDEFINED,
    NOTDEFINED,
}
