package buildingsmart.ifc;

public enum IfcFanTypeEnum {
    CENTRIFUGALFORWARDCURVED,
    CENTRIFUGALRADIAL,
    CENTRIFUGALBACKWARDINCLINEDCURVED,
    CENTRIFUGALAIRFOIL,
    TUBEAXIAL,
    VANEAXIAL,
    PROPELLORAXIAL,
    USERDEFINED,
    NOTDEFINED,
}
