package buildingsmart.ifc;

public enum IfcHumidifierTypeEnum {
    STEAMINJECTION,
    ADIABATICAIRWASHER,
    ADIABATICPAN,
    ADIABATICWETTEDELEMENT,
    ADIABATICATOMIZING,
    ADIABATICULTRASONIC,
    ADIABATICRIGIDMEDIA,
    ADIABATICCOMPRESSEDAIRNOZZLE,
    ASSISTEDELECTRIC,
    ASSISTEDNATURALGAS,
    ASSISTEDPROPANE,
    ASSISTEDBUTANE,
    ASSISTEDSTEAM,
    USERDEFINED,
    NOTDEFINED,
}
