package buildingsmart.ifc;

public enum IfcLampTypeEnum {
    COMPACTFLUORESCENT,
    FLUORESCENT,
    HIGHPRESSUREMERCURY,
    HIGHPRESSURESODIUM,
    METALHALIDE,
    TUNGSTENFILAMENT,
    USERDEFINED,
    NOTDEFINED,
}
