package buildingsmart.ifc;

public enum IfcLightEmissionSourceEnum {
    COMPACTFLUORESCENT,
    FLUORESCENT,
    HIGHPRESSUREMERCURY,
    HIGHPRESSURESODIUM,
    LIGHTEMITTINGDIODE,
    LOWPRESSURESODIUM,
    LOWVOLTAGEHALOGEN,
    MAINVOLTAGEHALOGEN,
    METALHALIDE,
    TUNGSTENFILAMENT,
    NOTDEFINED,
}
