package buildingsmart.ifc;

public enum IfcProtectiveDeviceTypeEnum {
    FUSEDISCONNECTOR,
    CIRCUITBREAKER,
    EARTHFAILUREDEVICE,
    RESIDUALCURRENTCIRCUITBREAKER,
    RESIDUALCURRENTSWITCH,
    VARISTOR,
    USERDEFINED,
    NOTDEFINED,
}
