package buildingsmart.ifc;

public enum IfcSensorTypeEnum {
    CO2SENSOR,
    FIRESENSOR,
    FLOWSENSOR,
    GASSENSOR,
    HEATSENSOR,
    HUMIDITYSENSOR,
    LIGHTSENSOR,
    MOISTURESENSOR,
    MOVEMENTSENSOR,
    PRESSURESENSOR,
    SMOKESENSOR,
    SOUNDSENSOR,
    TEMPERATURESENSOR,
    USERDEFINED,
    NOTDEFINED,
}
