package buildingsmart.ifc;

public enum IfcServiceLifeTypeEnum {
    ACTUALSERVICELIFE,
    EXPECTEDSERVICELIFE,
    OPTIMISTICREFERENCESERVICELIFE,
    PESSIMISTICREFERENCESERVICELIFE,
    REFERENCESERVICELIFE,
}
