package buildingsmart.ifc;

public enum IfcSpaceHeaterTypeEnum {
    SECTIONALRADIATOR,
    PANELRADIATOR,
    TUBULARRADIATOR,
    CONVECTOR,
    BASEBOARDHEATER,
    FINNEDTUBEUNIT,
    UNITHEATER,
    USERDEFINED,
    NOTDEFINED,
}
