package buildingsmart.ifc;

public enum IfcThermalLoadSourceEnum {
    PEOPLE,
    LIGHTING,
    EQUIPMENT,
    VENTILATIONINDOORAIR,
    VENTILATIONOUTSIDEAIR,
    RECIRCULATEDAIR,
    EXHAUSTAIR,
    AIREXCHANGERATE,
    DRYBULBTEMPERATURE,
    RELATIVEHUMIDITY,
    INFILTRATION,
    USERDEFINED,
    NOTDEFINED,
}
