package buildingsmart.ifc;

public enum IfcWindowPanelOperationEnum {
    SIDEHUNGRIGHTHAND,
    SIDEHUNGLEFTHAND,
    TILTANDTURNRIGHTHAND,
    TILTANDTURNLEFTHAND,
    TOPHUNG,
    BOTTOMHUNG,
    PIVOTHORIZONTAL,
    PIVOTVERTICAL,
    SLIDINGHORIZONTAL,
    SLIDINGVERTICAL,
    REMOVABLECASEMENT,
    FIXEDCASEMENT,
    OTHEROPERATION,
    NOTDEFINED,
}
