package buildingsmart.ifc;

public enum IfcWasteTerminalTypeEnum {
    FLOORTRAP,
    FLOORWASTE,
    GULLYSUMP,
    GULLYTRAP,
    GREASEINTERCEPTOR,
    OILINTERCEPTOR,
    PETROLINTERCEPTOR,
    ROOFDRAIN,
    WASTEDISPOSALUNIT,
    WASTETRAP,
    USERDEFINED,
    NOTDEFINED,
}
