// This file was automatically generated from IFCDOC at www.buildingsmart-tech.org.
// IFC content is copyright (C) 1996-2013 BuildingSMART International Ltd.

package buildingsmart.ifc
{
	public enum IfcRoleEnum
	{
		SUPPLIER,
		MANUFACTURER,
		CONTRACTOR,
		SUBCONTRACTOR,
		ARCHITECT,
		STRUCTURALENGINEER,
		COSTENGINEER,
		CLIENT,
		BUILDINGOWNER,
		BUILDINGOPERATOR,
		MECHANICALENGINEER,
		ELECTRICALENGINEER,
		PROJECTMANAGER,
		FACILITIESMANAGER,
		CIVILENGINEER,
		COMMISSIONINGENGINEER,
		ENGINEER,
		OWNER,
		CONSULTANT,
		CONSTRUCTIONMANAGER,
		FIELDCONSTRUCTIONMANAGER,
		RESELLER,
		USERDEFINED,
	}
}
