// This file was automatically generated from IFCDOC at www.buildingsmart-tech.org.
// IFC content is copyright (C) 1996-2013 BuildingSMART International Ltd.

package buildingsmart.ifc
{
	public enum IfcSensorTypeEnum
	{
		COSENSOR,
		CO2SENSOR,
		CONDUCTANCESENSOR,
		CONTACTSENSOR,
		FIRESENSOR,
		FLOWSENSOR,
		FROSTSENSOR,
		GASSENSOR,
		HEATSENSOR,
		HUMIDITYSENSOR,
		IDENTIFIERSENSOR,
		IONCONCENTRATIONSENSOR,
		LEVELSENSOR,
		LIGHTSENSOR,
		MOISTURESENSOR,
		MOVEMENTSENSOR,
		PHSENSOR,
		PRESSURESENSOR,
		RADIATIONSENSOR,
		RADIOACTIVITYSENSOR,
		SMOKESENSOR,
		SOUNDSENSOR,
		TEMPERATURESENSOR,
		WINDSENSOR,
		USERDEFINED,
		NOTDEFINED,
	}
}
