// This file was automatically generated from IFCDOC at https://technical.buildingsmart.org/.
// Very slight modifications were made to made content align with ifcXML reference examples.
// Use this class library to create IFC-compliant (web) applications with XML and JSON data.
// Author: Pieter Pauwels, Eindhoven University of Technology

package com.buildingsmart.tech.ifc.IfcMeasureResource;

public enum IfcUnitEnum
{
	ABSORBEDDOSEUNIT,
	AMOUNTOFSUBSTANCEUNIT,
	AREAUNIT,
	DOSEEQUIVALENTUNIT,
	ELECTRICCAPACITANCEUNIT,
	ELECTRICCHARGEUNIT,
	ELECTRICCONDUCTANCEUNIT,
	ELECTRICCURRENTUNIT,
	ELECTRICRESISTANCEUNIT,
	ELECTRICVOLTAGEUNIT,
	ENERGYUNIT,
	FORCEUNIT,
	FREQUENCYUNIT,
	ILLUMINANCEUNIT,
	INDUCTANCEUNIT,
	LENGTHUNIT,
	LUMINOUSFLUXUNIT,
	LUMINOUSINTENSITYUNIT,
	MAGNETICFLUXDENSITYUNIT,
	MAGNETICFLUXUNIT,
	MASSUNIT,
	PLANEANGLEUNIT,
	POWERUNIT,
	PRESSUREUNIT,
	RADIOACTIVITYUNIT,
	SOLIDANGLEUNIT,
	THERMODYNAMICTEMPERATUREUNIT,
	TIMEUNIT,
	VOLUMEUNIT,
	USERDEFINED,
}

