// This file was automatically generated from IFCDOC at https://technical.buildingsmart.org/.
// Very slight modifications were made to made content align with ifcXML reference examples.
// Use this class library to create IFC-compliant (web) applications with XML and JSON data.
// Author: Pieter Pauwels, Eindhoven University of Technology

package com.buildingsmart.tech.ifc.IfcGeometricModelResource;

import com.buildingsmart.tech.annotations.Description;
import com.buildingsmart.tech.annotations.Guid;
import com.buildingsmart.tech.annotations.Required;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

@Guid("3c76b659-a30a-44af-a964-3f20d2e22949")
@JsonIgnoreProperties(ignoreUnknown=true)
public class IfcSurfaceCurveSweptAreaSolid extends IfcSweptAreaSolid
{
	@JacksonXmlProperty(isAttribute=false, localName = "Directrix")
	@Description("The curve used to define the sweeping operation. The solid is generated by sweeping the <em>SELF\\IfcSweptAreaSolid.SweptArea</em> along the <em>Directrix</em>.")
	@Required()
	@Guid("49b50318-7752-47d8-95a2-b909aa00bad8")
	private com.buildingsmart.tech.ifc.IfcGeometryResource.IfcCurve directrix;

	@JacksonXmlProperty(isAttribute=true, localName = "StartParam")
	@Description("The parameter value on the <em>Directrix</em> at which the sweeping operation commences. If no value is provided the start of the sweeping operation is at the start of the <em>Directrix</em>.   <blockquote class=\"change-ifc2x4\">IFC4 CHANGE&nbsp; The attribute has been changed to OPTIONAL with upward compatibility for file-based exchange.</blockquote>")
	@Guid("3b7320f4-3ba7-4832-acde-ad54018261d6")
	private double startParam;

	@JacksonXmlProperty(isAttribute=true, localName = "EndParam")
	@Description("The parameter value on the <em>Directrix</em> at which the sweeping operation ends. If no value is provided the end of the sweeping operation is at the end of the <em>Directrix</em>.   <blockquote class=\"change-ifc2x4\">IFC4 CHANGE&nbsp; The attribute has been changed to OPTIONAL with upward compatibility for file-based exchange.</blockquote>")
	@Guid("07f28201-d83f-4d2b-9102-dba02a68c213")
	private double endParam;

	@JacksonXmlProperty(isAttribute=false, localName = "ReferenceSurface")
	@Description("The surface containing the <em>Directrix</em>.")
	@Required()
	@Guid("89366c6f-97ce-4ee1-8b33-eeda99031116")
	private com.buildingsmart.tech.ifc.IfcGeometryResource.IfcSurface referenceSurface;


	public IfcSurfaceCurveSweptAreaSolid()
	{
	}

	public IfcSurfaceCurveSweptAreaSolid(com.buildingsmart.tech.ifc.IfcProfileResource.IfcProfileDef sweptArea, com.buildingsmart.tech.ifc.IfcGeometryResource.IfcCurve directrix, com.buildingsmart.tech.ifc.IfcGeometryResource.IfcSurface referenceSurface)
	{
		super(sweptArea);
		this.directrix = directrix;
		this.referenceSurface = referenceSurface;
	}

	public com.buildingsmart.tech.ifc.IfcGeometryResource.IfcCurve getDirectrix() {
		return this.directrix;
	}

	public void setDirectrix(com.buildingsmart.tech.ifc.IfcGeometryResource.IfcCurve directrix) {
		this.directrix = directrix;
	}

	public double getStartParam() {
		return this.startParam;
	}

	public void setStartParam(double startParam) {
		this.startParam = startParam;
	}

	public double getEndParam() {
		return this.endParam;
	}

	public void setEndParam(double endParam) {
		this.endParam = endParam;
	}

	public com.buildingsmart.tech.ifc.IfcGeometryResource.IfcSurface getReferenceSurface() {
		return this.referenceSurface;
	}

	public void setReferenceSurface(com.buildingsmart.tech.ifc.IfcGeometryResource.IfcSurface referenceSurface) {
		this.referenceSurface = referenceSurface;
	}


}

