// This file was automatically generated from IFCDOC at www.buildingsmart-tech.org.
// IFC content is copyright (C) 1996-2013 BuildingSMART International Ltd.

package buildingsmart.ifc
{
	public enum IfcElectricApplianceTypeEnum
	{
		COMPUTER,
		DIRECTWATERHEATER,
		DISHWASHER,
		ELECTRICCOOKER,
		ELECTRICHEATER,
		FACSIMILE,
		FREESTANDINGFAN,
		FREEZER,
		FRIDGE_FREEZER,
		HANDDRYER,
		INDIRECTWATERHEATER,
		MICROWAVE,
		PHOTOCOPIER,
		PRINTER,
		REFRIGERATOR,
		RADIANTHEATER,
		SCANNER,
		TELEPHONE,
		TUMBLEDRYER,
		TV,
		VENDINGMACHINE,
		WASHINGMACHINE,
		WATERHEATER,
		WATERCOOLER,
		USERDEFINED,
		NOTDEFINED,
	}
}
